# 跨子网多从臂注册表（cross_subnet launch 可选）
# robot_id 须与 launch 参数 robot_id:=<id> 一致
slaves:
  - id: ar5_01
    ip: 192.168.8.78
    local_ips: ["192.168.8.78", "10.18.64.46"]
    network_interface: eno1
  - id: fr3v2_1_01
    ip: 192.168.8.78
    local_ips: ["192.168.8.78", "10.0.0.10"]
    network_interface: eno1
  # - id: fr3v2_1_02
  #   ip: 192.168.8.79
  #   local_ips: ["192.168.8.79"]
  #   network_interface: eno1
