actuators:
  joint1:
    type: motor
    gear: 1
    ctrlrange:
    - -30.0
    - 30.0
    forcerange:
    - -30.0
    - 30.0
  joint2:
    type: motor
    gear: 1
    ctrlrange:
    - -100.0
    - 100.0
    forcerange:
    - -100.0
    - 100.0
  joint3:
    type: motor
    gear: 1
    ctrlrange:
    - -30.0
    - 30.0
    forcerange:
    - -30.0
    - 30.0
  joint4:
    type: motor
    gear: 1
    ctrlrange:
    - -10.0
    - 10.0
    forcerange:
    - -10.0
    - 10.0
  joint5:
    type: motor
    gear: 1
    ctrlrange:
    - -10.0
    - 10.0
    forcerange:
    - -10.0
    - 10.0
  joint6:
    type: motor
    gear: 1
    ctrlrange:
    - -10.0
    - 10.0
    forcerange:
    - -10.0
    - 10.0
  joint7:
    type: motor
    gear: 1
    ctrlrange:
    - -3.0
    - 3.0
    forcerange:
    - -3.0
    - 3.0
  joint8:
    type: motor
    gear: 1
    ctrlrange:
    - -3.0
    - 3.0
    forcerange:
    - -3.0
    - 3.0
scene:
  timestep: 0.002
  gravity:
  - 0
  - 0
  - -9.81
  lighting: true
  ground: true
geom_properties:
  base_link:
    contype: 0
    conaffinity: 0
    density: 0
    group: 1
  link1:
    contype: 1
    conaffinity: 15
    density: 0
    group: 0
  link2:
    contype: 1
    conaffinity: 15
    density: 0
    group: 0
  link3:
    contype: 1
    conaffinity: 15
    density: 0
    group: 0
  link4:
    contype: 1
    conaffinity: 15
    density: 0
    group: 0
  link5:
    contype: 1
    conaffinity: 15
    density: 0
    group: 0
  link6:
    contype: 1
    conaffinity: 15
    density: 0
    group: 0
  link7:
    contype: 1
    conaffinity: 15
    density: 0
    group: 0
  link8:
    contype: 1
    conaffinity: 15
    density: 0
    group: 0
