nexus_arm_simulator:
  ros__parameters:
    # Model path - relative to package share directory
    model_path: "robot_description/nexus-arm_v15_right_description/mjcf/nexus-arm-right.xml"

    # robot name，用来作为 topic 前缀，比如 /my_robot/rt/teleop/...
    robot_name: "nexus_arm_master"

    # Robot type for gripper mapping logic
    robot_type: "nexus_arm_v15_right"

    # Publishing rate in Hz
    publish_rate: 500.0

    # Enable MuJoCo viewer window
    enable_viewer: true

    # Arm status publishing rate in Hz
    arm_status_rate: 10.0

    # Topic names
    joint_mit_control_topic: '/teleop/joint_cmd'
    joint_state_topic: '/teleop/joint_states'
    status_topic: '/teleop/arm_status'
    end_pose_topic: '/teleop/end_pose'

    # Gripper mapping configuration
    enable_gripper_mapping: true
    gripper_joint_index: 6  # gripper_Joint is at index 6 (0-based indexing)

    # End effector site configuration
    enable_end_pose: false
