/**:
  ros__parameters:
    robot_name: "nexus_arm_master"
    robot_type: "nexus-arm-v15-right"
    urdf_path: "package://human_data/urdf/nexus-arm-v15-right.urdf"
    robot_base_frame: "base_link"
    model_configuration: ["right_wrist", "right_end_effector"]
    publish_rate: 200.0  # 发布频率(Hz)

    # ==================== configuration ====================
    model_configs:
      right_wrist:
        type: "ee"
        base_link: "base_link"
        end_effector_link: "force_Link"
        joint_indices: [0, 1, 2, 3, 4, 5]
        joint_names: ["right_joint1", "right_joint2", "right_joint3", "right_joint4", "right_joint5", "right_joint6"]
        base_position_matrix: [1.0, 0.0, 0.0, 0.0,
                                    0.0, 1.0, 0.0, 0.0,
                                    0.0, 0.0, 1.0, 0.0,
                                    0.0, 0.0, 0.0, 1.0]
      right_end_effector:
        type: "gripper"
        joint_indices: [6]
        joint_names: ["right_joint7"]


    # ==================== ros2 topic ====================
    joint_state_topic: "/teleop/joint_states"

    human_data_topic: "/teleop/human_data"

    pedal_state_topic: "/teleop/pedal_state"
