master_nexus_adapter:
  ros__parameters:
    # robot name，用来作为 topic 前缀，比如 /my_robot/rt/teleop/...
    robot_name: "nexus_arm_master"

    adapter_type: "teleop"   # "teleop" 或 "y1"
    # right_arm parameters: configuration for the right robotic arm

    right_arm_port: '/dev/nexus_arm'

    right_arm_feedback_rate: 500
    right_arm_num_of_dofs: 7

  # whether to enable robotic arm 
    auto_enable: true

    joint_mit_control_topic: 'teleop/joint_cmd'

    # end pose and joint position feedback 
    joint_state_topic: 'teleop/joint_states'

    # joint motor status feedback 
    status_topic: 'teleop/arm_status'

    #only teleop arm has peripheral interface
    gripper_key_state_topic: 'teleop/gripper_key'
    peripheral_command_topic: 'teleop/peripheral_cmd'

    # total number of degrees of freedom (DOFs) for both arms combined
    num_of_dofs: 7

    # names of all joints in order (right arm joints followed by left arm joints)
    joint_names: ["right_joint1", "right_joint2", "right_joint3",
                  "right_joint4", "right_joint5", "right_joint6","right_joint7"]

    # mapping indices from device joint order to ROS joint_states message order
    joint_mapping: [0, 1, 2, 3, 4, 5, 6]